sudo: required

language: c++

dist: "bionic"

before_install:
  - git clone https://github.com/emscripten-core/emsdk
  - emsdk/emsdk install latest
  - emsdk/emsdk activate latest
  - . emsdk/emsdk_env.sh
  - python3 --version

script:
    - make WEB=1 # Compile files
    - rm -rf obj # Clean intermediate compilation files
    - mkdir -p gh-pages # Create gh-pages directory (local-dir)
    - mv index.{html,js,wasm} img gh-pages # Move the resulting files to that directory

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  committer-from-gh: true
  local-dir: gh-pages
  on:
    branch: master
