pipeline:
        build-web:
                image: archlinux:base-devel
                commands:
                        - pacman -Syu --noconfirm emscripten
                        - source /etc/profile.d/emscripten.sh
                        - em++ --version
                        - make WEB=1
                when:
                        - event: pull_request
                        - event: push
                          branch: master

        publish-web:
                image: archlinux:base-devel
                secrets: [mail, codeberg_token]
                commands:
                        - pacman -Syu --noconfirm git
                        - git config --global user.email $MAIL
                        - git config --global user.name "Codeberg CI"
                        - git clone -b pages https://$CODEBERG_TOKEN@codeberg.org/$CI_REPO.git $CI_REPO_NAME
                        - mv index.{html,js,wasm,data} img $CI_REPO_NAME
                        - cd $CI_REPO_NAME
                        - git add .
                        - git commit -m "Codeberg CI $CI_BUILD_CREATED"
                        - git push
                when:
                        event: push
                        branch: master

when:
        - event: pull_request
        - event: push
          branch: master
